---
# NCNR Specific Tasks

- name: "NCNR | 5.2.4 | PATCH | Ensure SSH X11 forwarding is enabled, we like it"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding yes'
  tags:
      - level1
      - level2
      - patch
      - rule_5.2.4
      - ncnr

- name: "NCNR | Create tenscan user"
  user:
      name: tenscan
      groups: sudo
      state: present
  tags: 
      - level1
      - tenscan
      - patch
      - ncnr

- name: "NCNR | Set tenscan user RSA key"
  authorized_key:
      user: tenscan
      key: http://network.ncnr.nist.gov/tenscan_rsa.pub
      state: present
  tags: 
      - level1
      - tenscan
      - patch
      - ncnr

- name: "NCNR | Set files to 644 so tenable can read them"
  file:
      dest: "{{ item }}"
      state: file
      owner: root
      group: root
      mode: 0644
  with_items:
      - /etc/modprobe.d/CIS.conf
      - /etc/audit/auditd.conf
      - /etc/audit/audit.rules
      - /etc/default/useradd
  tags:
      - level1
      - patch
      - ncnr

- name: "NCNR | Set directories to 755 so tenable can read them"
  file:
      dest: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
  with_items:
      - /etc/audit
      - /var/spool/cron
  tags:
      - level1
      - patch
      - ncnr
